BOOKSTORE = {
    ["Name"] = "BookStore",
    ["Version"] = "8.0.0",
}

if (GetLocale() == "frFR") then 
 
 
 
    BOOKSTORE_INIT = BOOKSTORE.Name .. " v" .. BOOKSTORE.Version .. " s'est correctement initialis\195\169. Bonne Lecture!";
    BOOKSTORE_EXISTS = " existe déjà dans " .. BOOKSTORE.Name .. ".";
    BOOKSTORE_ADDED = " a \195\169t\195\169 ajout\195\169 \195\160 l'archive " .. BOOKSTORE.Name .. " avec succ\195\168s";
    BOOKSTORE_FULL = "Votre " .. BOOKSTORE.Name .. " est actuellement plein, vous devez d\195\169truire un livre avant de pouvoir en ajouter un nouveau.";
    BOOKSTORE_OPENSHELF = "Ouverture " .. BOOKSTORE.Name .. " Étagère ";
    BOOKSTORE_SHELF = "Shelf ";
    BOOKSTORE_SHELF_ONLY = "Étagère";
    BOOKSTORE_BOOK_ONLY = "livre";
    BOOKSTORE_SEARCH_FOR = BOOKSTORE.Name .. " à la recherche de: ";
    BOOKSTORE_SEARCH_TOOLTIP = "Recherche la bibliothèque BookStore."
    BOOKSTORE_BUTTON_DELETE = "Supprimer ce Livre";
    BOOKSTORE_BUTTON_RENAME = "Renommez ce livre";
    BOOKSTORE_BUTTON_RENAME_TOOLTIP = "Changer ou ajouter au\ntitre de ce livre.";
    BOOKSTORE_BUTTON_EXPORT = "Import/Export.";
    BOOKSTORE_BUTTON_EXPORT_V = "Import/\nExport";
    BOOKSTORE_BUTTON_EXPORT_TOOLTIP = "Exportez le livre actuel ou\nimportez un nouveau livre.";
    BOOKSTORE_BUTTON_OTHERNAME = "Ce titre existe déjà dans la librairie.\nVeuillez entrer un nouveau titre ou annuler.";
    BOOKSTORE_BUTTON_COPY = "Faire une Copie";
    BOOKSTORE_PAGES = " Pages";
    BOOKSTORE_MINIMAP_TOOLTIP = "Manifester " .. BOOKSTORE.Name;
    BOOKSTORE_HELP = "/bookstore ouvre et tire la bibliothèque " .. BOOKSTORE.Name .. "\nSyntax: /bookstore\n/bookstore mm active et désactive l'icône MiniMap\nSyntax: /bookstore mm\n/bookstore mr Réinitialiser la position de l'icône MiniMap\nSyntax: /bookstore mr\n/bookstore mf Alignez ou détachez la position de l'icône MiniMap du MiniMap\nSyntax: /bookstore mf\n/bookstore help affiche le message dirdse\nSyntax: /bookstore help\n/bookstore options ouvre la fenêtre des options\nSyntax: /bookstore options\n";
    BOOKSTORE_TITLE_CHANGE = "Veuillez saisir un nouveau titre."
    BOOKSTORE_IMPORT_BOOK = "Exporter: copiez le texte (CTRL + C) et donnez-le à vos amis\nImporter: coller un texte et cliquer sur \"Import\""
    BOOKSTORE_HAVE = "Stock: ";
    BOOKSTORE_EMPTY = BOOKSTORE_HAVE .. " pas de livres.";
    BOOKSTORE_BOOKS = " livres.";
    BOOKSTORE_MENU = "BookStore";
    BOOKSTORE_MENU_DISPLAY = "Afficher " .. BOOKSTORE.Name;
    BOOKSTORE_MENU_DISPLAY_MM = "Afficher l'icône MiniMap";
    BOOKSTORE_AUTHOR = "Auteur: ";
    BOOKSTORE_CREATOR = "Créé par: ";
    BOOKSTORE_MM_TOOLTIP = "\nClic gauche:     Afficher/masquer l'étagère\nClic-droit:         ouvrir Options/déplacer cette icône\nClic du milieu:  Activer/désactiver en faisant glisser\n                            l'icône le long de la MiniMap";
    BOOKSTORE_MM_RESETPOSITION = "Bouton MiniMap Réinitialiser";
    BOOKSTORE_MM_FIXPOSITION = "Attacher le bouton MiniMap au MiniMap?";
    BOOKSTORE_MM_FIXPOSITION_COMM = "Protège le bouton MiniMap contre tout déplacement accidentel.";
    BOOKSTORE_MM_SHOWBUTTON = "Afficher l'icône MiniMap? (Nécessite un redémarrage)";
    BOOKSTORE_MM_SHOWBUTTON_COMM = "Affichez ou masquez l'icône sur la MiniMap. Pour prendre effet, l'interface utilisateur ou WoW doit être redémarré.";
    BOOKSTORE_SETWINPOSITION = "Fixer les positions des fenêtres?";
    BOOKSTORE_SETWINPOSITION_COMM ="Cela aide également si les fenêtres sont accidentellement déplacées hors de la zone visible. Pour ce faire, activez cette fonction, puis déconnectez-vous et reconnectez-vous. Après cela, toutes les fenêtres doivent être en position standard et vous pouvez à nouveau désactiver cette fonction.";
    BOOKSTORE_SORT_TITLE = "Titre"
    BOOKSTORE_SORT_TITLE_TT = "Trie la collection de livres par titre."
    BOOKSTORE_SORT_DATE = "Date"
    BOOKSTORE_SORT_DATE_TT = "Trie la collection de livres par date."
    BOOKSTORE_SORT_LOC = "Endroit"
    BOOKSTORE_SORT_LOC_TT = "Trie la collection de livres en fonction\nde l'endroit où elle a été trouvée"
    BOOKSTORE_SORT_CREATOR = "Créateur"
    BOOKSTORE_SORT_CREATOR_TT = "Trie la collection de livres en fonction du chercheur."
    BOOKSTORE_SORT_AUTHOR = "Auteur"
    BOOKSTORE_SORT_AUTHOR_TT = "Trie la collection de livres en fonction du auteur."
    BOOKSTORE_SORT_TOGGLE = "Asc./\ndesc."
    BOOKSTORE_SORT_TOGGLE_TT = "Bascule entre l'ordre croissant et décroissant."
    BOOKSTORE_IMPORT_DB_TEXT = "Lemmos BookStore reborn database import"
    BOOKSTORE_IMPORT_DB_KNOWN_ONLY = "Ajouter uniquement\ndes livres inconnus"
    BOOKSTORE_IMPORT_DB_RESET = "Supprimer la base de données\net importer les données standard"
    BOOKSTORE_IMPORT_DB_RESET_CONFIRM = "Voulez-vous vraiment supprimer la base de\ndonnées existante et la remplacer par la\ncollection de livres standard?\n\n!!! Cela ne peut pas être inversé !!!"
    BOOKSTORE_SEARCH_STATISTICS1 = " livres pour un total de "
    BOOKSTORE_SEARCH_STATISTICS2 = " pages trouvées."

elseif (GetLocale() == "deDE") then 



    BOOKSTORE_INIT = BOOKSTORE.Name .. " v" .. BOOKSTORE.Version .. " wurde erfolgreich geladen, frohes Lesen!";
    BOOKSTORE_EXISTS = " existiert schon in " .. BOOKSTORE.Name .. ".";
    BOOKSTORE_ADDED = " Erflogreich hinzugefügt zu " .. BOOKSTORE.Name .. " Sammlung";
    BOOKSTORE_FULL = "Euer " .. BOOKSTORE.Name .. " ist leider voll !!! Löscht ein Buch um ein weiteres hinzufügen zu können.";
    BOOKSTORE_OPENSHELF = "" .. BOOKSTORE.Name .. " Buchregal wird geöffnet ";
    BOOKSTORE_SHELF = "Regal ";
    BOOKSTORE_SHELF_ONLY = "Regal";
    BOOKSTORE_BOOK_ONLY = "Buch";
    BOOKSTORE_SEARCH_FOR = BOOKSTORE.Name .. " Suche nach: ";
    BOOKSTORE_SEARCH_TOOLTIP = "Durchsucht die BookStore Bibliothek."
    BOOKSTORE_BUTTON_DELETE = "Dieses Buch löschen";
    BOOKSTORE_BUTTON_RENAME = "Dieses Buch Umbenennen";
    BOOKSTORE_BUTTON_RENAME_TOOLTIP = "Den Titel dieses Buches\nändern oder ergänzen.";
    BOOKSTORE_BUTTON_EXPORT = "Import/Export.";
    BOOKSTORE_BUTTON_EXPORT_V = "Import/\nExport";
    BOOKSTORE_BUTTON_EXPORT_TOOLTIP = "Das aktuelle Buch exportieren oder\nein neues Buch importieren.";
    BOOKSTORE_BUTTON_OTHERNAME = "Dieser Titel existiert bereits im BookStore.\nBitte einen neuen Titel eingeben oder abbrechen.";
    BOOKSTORE_BUTTON_COPY = "Buch kopieren";
    BOOKSTORE_PAGES = " Seiten";
    BOOKSTORE_MINIMAP_TOOLTIP = "Anzeigen/Verstecken " .. BOOKSTORE.Name;
    BOOKSTORE_HELP = "/bookstore öffnet und schießt das " .. BOOKSTORE.Name .. " Buchregal\nSyntax: /bookstore\n/bookstore mm MiniMap icon Anzeigen und Verstecken\n(UI muss zum verstecken neu geladen werden)\nSyntax: /bookstore mm\n/bookstore mr MiniMap Iconposition zurücksetzen\nSyntax: /bookstore mr\n/bookstore mf MiniMap Iconposition an der Minimap ausrichten oder davon lösen\nSyntax: /bookstore mf\n/bookstore help diese Hilfe anzeigen\nSyntax: /bookstore help\n/bookstore -f Nach einem Buchtitel suchen\nSyntax: /bookstore -f das Buch nach dem du suchst\n/bookstore options öffnet das Optionsfenster\nSyntax: /bookstore options\n";
    BOOKSTORE_TITLE_CHANGE = "Bitte einen neuen Titel eingeben."
    BOOKSTORE_IMPORT_BOOK = "Export: kopiert den Text (STRG+C) und gebt ihn Euren Freunden\nImport: fügt ein Importstring ein und klickt unten auf \"Import\""
    BOOKSTORE_HAVE = "Du hast ";
    BOOKSTORE_EMPTY = BOOKSTORE_HAVE .. " keine Bücher.";
    BOOKSTORE_BOOKS = " Bücher.";
    BOOKSTORE_MENU = "BookStore";
    BOOKSTORE_MENU_DISPLAY = "Zeige " .. BOOKSTORE.Name;
    BOOKSTORE_MENU_DISPLAY_MM = "Zeige Minimap Icon";
    BOOKSTORE_AUTHOR = "Autor: ";
    BOOKSTORE_CREATOR = "Kopiert von: ";
    BOOKSTORE_MM_TOOLTIP = "\nLinksklick:    Regal zeigen/verstecken\nRechtsklick: Optionen öffnen/Icon verschieben\nMittelklick:  MiniMap Icon sperren/entsperren";
    BOOKSTORE_MM_RESETPOSITION = "MiniMap Button zurücksetzen";
    BOOKSTORE_MM_FIXPOSITION = "MiniMap Button an der MiniMap fixieren?";
    BOOKSTORE_MM_FIXPOSITION_COMM = "Schützt den MiniMap Button vor einem versehentlichen Verschieben.";
    BOOKSTORE_MM_SHOWBUTTON = "MiniMap Button anzeigen? ( Neustart erforderlich )";
    BOOKSTORE_MM_SHOWBUTTON_COMM = "Icon an der MiniMap anzeigen oder verstecken.\nUm wirksam zu werden muss das UI oder WoW neu gestartet werden.";
    BOOKSTORE_SETWINPOSITION = "Fensterpositionen fixieren?";
    BOOKSTORE_SETWINPOSITION_COMM ="Dies hilft auch dabei wenn Fenster versehentlich außerhalb des sichtbaren Bereichs geschoben wurden.\nHierzu diese Funktion aktivieren, dann ausloggen und wieder einloggen. Danach sollten alle Fenster an der Standardposition sein und man kann diese Funktion wieder deaktivieren.";
    BOOKSTORE_SORT_TITLE = "Titel"
    BOOKSTORE_SORT_TITLE_TT = "Sortiert die Buchsammlung nach Titel."
    BOOKSTORE_SORT_DATE = "Datum"
    BOOKSTORE_SORT_DATE_TT = "Sortiert die Buchsammlung nach Datum."
    BOOKSTORE_SORT_LOC = "Fundort"
    BOOKSTORE_SORT_LOC_TT = "Sortiert die Buchsammlung nach dem Fundort"
    BOOKSTORE_SORT_CREATOR = "Ersteller"
    BOOKSTORE_SORT_CREATOR_TT = "Sortiert die Buchsammlung nach dem Finder."
    BOOKSTORE_SORT_AUTHOR = "Autor"
    BOOKSTORE_SORT_AUTHOR_TT = "Sortiert die Buchsammlung nach dem Autor."
    BOOKSTORE_SORT_TOGGLE = "Aufst./\nabst."
    BOOKSTORE_SORT_TOGGLE_TT = "Wechselt zwischen der aufsteigenden und der\nabsteigenden Reihenfolge."
    BOOKSTORE_IMPORT_DB_TEXT = "Lemmos BookStore reborn Datenbankimport"
    BOOKSTORE_IMPORT_DB_KNOWN_ONLY = "Nur unbekannte\nBücher importieren"
    BOOKSTORE_IMPORT_DB_RESET = "Datenbank löschen und\nStandardbücher importieren"
    BOOKSTORE_IMPORT_DB_RESET_CONFIRM = "Wirklich die bestehende Datenbank\nlöschen und mit der Standardbuchsammlung\nersetzen?\n\nDies kann nicht rückgängig gemacht werden !!!"
    BOOKSTORE_SEARCH_STATISTICS1 = " Bücher, mit insgesamt "
    BOOKSTORE_SEARCH_STATISTICS2 = " Seiten gefunden."
	
	elseif (GetLocale() == "ruRU") then 
	
	
	
	BOOKSTORE_INIT = BOOKSTORE.Name .. " v" .. BOOKSTORE.Version .. " успешно инициализирован, удачного чтения!";
    BOOKSTORE_EXISTS = " уже существует в " .. BOOKSTORE.Name .. ".";
    BOOKSTORE_ADDED = " успешно добавлен в " .. BOOKSTORE.Name .. " коллекция.";
    BOOKSTORE_FULL = "Ваш " .. BOOKSTORE.Name .. " в настоящее время заполнено. Вы должны удалить книгу, прежде чем сможете добавить новую.";
    BOOKSTORE_OPENSHELF = "Открытие " .. BOOKSTORE.Name .. " Полка ";
    BOOKSTORE_SHELF = "Полка ";
    BOOKSTORE_SHELF_ONLY = "Полка";
    BOOKSTORE_BOOK_ONLY = "Книга";
    BOOKSTORE_SEARCH_FOR = BOOKSTORE.Name .. " в поисках: ";
    BOOKSTORE_SEARCH_TOOLTIP = "Ищет в библиотеке."
    BOOKSTORE_BUTTON_DELETE = "Удалить эту книгу";
    BOOKSTORE_BUTTON_RENAME = "Переименовать эту книгу";
    BOOKSTORE_BUTTON_RENAME_TOOLTIP = "Измените название или добавьте комментарии\nк названию этой книги.";
    BOOKSTORE_BUTTON_EXPORT = "Импорт/Экспорт.";
    BOOKSTORE_BUTTON_EXPORT_V = "Импорт/\nЭкспорт";
    BOOKSTORE_BUTTON_EXPORT_TOOLTIP = "Экспортируйте текущую книгу\nи не импортируйте новую книгу.";
    BOOKSTORE_BUTTON_OTHERNAME = "Эта книга уже есть в Книжном.\nПожалуйста, введите новое название или отмените.";
    BOOKSTORE_BUTTON_COPY = "Сделать копию";
    BOOKSTORE_PAGES = " Страницы";
    BOOKSTORE_MINIMAP_TOOLTIP = "Показать/Скрыть " .. BOOKSTORE.Name;
    BOOKSTORE_HELP = "/bookstore переключить " .. BOOKSTORE.Name .. " открыть и закрыть\nКоманда: /bookstore\n/включить или отключить иконку книжного на миникарте\nКоманда: /bookstore mm\n/сбросить положение книжного на миникарте\nКоманда: /bookstore mr\n/Выровняйте или отсоедините положение значка книжного на миникарте\nКоманда: /bookstore mf\n/помогите распечатать это сообщение\nКоманда: /bookstore help\n/поиск по названию книги\nКоманда: /название книги, которую вы ищете\n/открывает окно параметров\nКоманда: /bookstore options\n";
    BOOKSTORE_TITLE_CHANGE = "Пожалуйста, введите новое название."
    BOOKSTORE_IMPORT_BOOK = "Экспорт: скопируйте эту строку (CTRL+C) и поделитесь со своими друзьями\nИмпорт: вставьте строку импорта и щелкните \"Импорт\""
    BOOKSTORE_HAVE = "У вас есть ";
    BOOKSTORE_EMPTY = BOOKSTORE_HAVE .. " нет книг.";
    BOOKSTORE_BOOKS = " книга(и).";
    BOOKSTORE_MENU = "BookStore";
    BOOKSTORE_MENU_DISPLAY = "Показать " .. BOOKSTORE.Name;
    BOOKSTORE_MENU_DISPLAY_MM = "Показать значок на миникарте";
    BOOKSTORE_AUTHOR = "Автор:";
    BOOKSTORE_CREATOR = "Скопировано: ";
    BOOKSTORE_MM_TOOLTIP = "ЛКМ:       показать/скрыть полку\nПКМ:     Открыть параметры/переместить этот значок\nСКМ: включить/выключить прикрепление к миникарте.";
    BOOKSTORE_MM_RESETPOSITION = "Кнопка сброса иконки на миникарте";
    BOOKSTORE_MM_FIXPOSITION = "Прикрепить кнопку к миникарте?";
    BOOKSTORE_MM_FIXPOSITION_COMM = "Защищает кнопку на миникарте от случайного перемещения.";
    BOOKSTORE_MM_SHOWBUTTON = "Показать значок на миникарте? (Требуется перезагрузка)";
    BOOKSTORE_MM_SHOWBUTTON_COMM = "Показать или скрыть значок на миникарте. Чтобы вступило в силу, необходимо перезагрузить интерфейс или WoW.";
    BOOKSTORE_SETWINPOSITION = "Исправить положение окон?";
    BOOKSTORE_SETWINPOSITION_COMM = "Это также помогает, если окна случайно перемещаются за пределы видимой области. Для этого активируйте эту функцию, затем выйдите из игры и снова войдите в игру. После этого все окна должны быть в стандартном положении, и вы можете снова отключить эту функцию.";
    BOOKSTORE_SORT_TITLE = "Название"
    BOOKSTORE_SORT_TITLE_TT = "Сортировка коллекции книг по названию. "
    BOOKSTORE_SORT_DATE = "Дата"
    BOOKSTORE_SORT_DATE_TT = "Сортировка коллекции книг по дате."
    BOOKSTORE_SORT_LOC = "Место"
    BOOKSTORE_SORT_LOC_TT = "Сортирует коллекцию книг по месту ее обнаружения."
    BOOKSTORE_SORT_CREATOR = "Создатель"
    BOOKSTORE_SORT_CREATOR_TT = "Сортирует книжную коллекцию по искателю."
    BOOKSTORE_SORT_AUTHOR = "Автор"
    BOOKSTORE_SORT_AUTHOR_TT = "Сортирует книжную коллекцию по автору."
    BOOKSTORE_SORT_TOGGLE = "Asc./\ndesc."
    BOOKSTORE_SORT_TOGGLE_TT = "Переключение между возрастающим и убывающим порядком."
    BOOKSTORE_IMPORT_DB_TEXT = "Lemmos BookStore reborn импорт базы данных"
    BOOKSTORE_IMPORT_DB_KNOWN_ONLY = "Добавить неизвестное\nтолько книги"
    BOOKSTORE_IMPORT_DB_RESET = "Удалить базу данных и\nимпортировать стандартные данные"
    BOOKSTORE_IMPORT_DB_RESET_CONFIRM = "Вы уверены, что хотите удалить существующую базу данных\nи заменить его стандартным собранием книг?\n\n!!! Это не может быть отменено !!!"
    BOOKSTORE_SEARCH_STATISTICS1 = " книг найдено в общей сложности "
    BOOKSTORE_SEARCH_STATISTICS2 = " страницы."
	
else
 
    BOOKSTORE_INIT = BOOKSTORE.Name .. " v" .. BOOKSTORE.Version .. " successfully initialised, happy reading!";
    BOOKSTORE_EXISTS = " already exists in " .. BOOKSTORE.Name .. ".";
    BOOKSTORE_ADDED = " successfully added to " .. BOOKSTORE.Name .. " collection.";
    BOOKSTORE_FULL = "Your " .. BOOKSTORE.Name .. " is currently full. You must delete a book before you can add a new one.";
    BOOKSTORE_OPENSHELF = "Opening " .. BOOKSTORE.Name .. " Shelf ";
    BOOKSTORE_SHELF = "Shelf ";
    BOOKSTORE_SHELF_ONLY = "Shelf";
    BOOKSTORE_BOOK_ONLY = "Book";
    BOOKSTORE_SEARCH_FOR = BOOKSTORE.Name .. " searching for: ";
    BOOKSTORE_SEARCH_TOOLTIP = "Searches the BookStore library."
    BOOKSTORE_BUTTON_DELETE = "Delete this Book";
    BOOKSTORE_BUTTON_RENAME = "Rename this Book";
    BOOKSTORE_BUTTON_RENAME_TOOLTIP = "Change the title or add comments\nto the title of this book.";
    BOOKSTORE_BUTTON_EXPORT = "Import/Export.";
    BOOKSTORE_BUTTON_EXPORT_V = "Import/\nExport";
    BOOKSTORE_BUTTON_EXPORT_TOOLTIP = "Export the current book\nor import a new book.";
    BOOKSTORE_BUTTON_OTHERNAME = "This book already exists in the BookStore.\nPlease enter a new title or cancel.";
    BOOKSTORE_BUTTON_COPY = "Make A Copy";
    BOOKSTORE_PAGES = " Pages";
    BOOKSTORE_MINIMAP_TOOLTIP = "Show/Hide " .. BOOKSTORE.Name;
    BOOKSTORE_HELP = "/bookstore toggles " .. BOOKSTORE.Name .. " open and close\nSyntax: /bookstore\n/bookstore mm toggles MiniMap icon on and off\nSyntax: /bookstore mm\n/bookstore mr Reset MiniMap icon position\nSyntax: /bookstore mr\n/bookstore mf Align or detach the MiniMap icon position from the MiniMap\nSyntax: /bookstore mf\n/bookstore help print this message\nSyntax: /bookstore help\n/bookstore -f Search for a book title\nSyntax: /bookstore -f book title that you are searching for\n/bookstore options opens the options window\nSyntax: /bookstore options\n";
    BOOKSTORE_TITLE_CHANGE = "Please enter a new title."
    BOOKSTORE_IMPORT_BOOK = "Export: copy this string (CTRL+C) and give it to your friends\nImport: paste a importstring and click \"Import\""
    BOOKSTORE_HAVE = "You have ";
    BOOKSTORE_EMPTY = BOOKSTORE_HAVE .. " no books.";
    BOOKSTORE_BOOKS = " book(s).";
    BOOKSTORE_MENU = "BookStore";
    BOOKSTORE_MENU_DISPLAY = "Show " .. BOOKSTORE.Name;
    BOOKSTORE_MENU_DISPLAY_MM = "Show Minimap Icon";
    BOOKSTORE_AUTHOR = "Author:";
    BOOKSTORE_CREATOR = "Copied by: ";
    BOOKSTORE_MM_TOOLTIP = "Left click:       show/hide shelf\nRight click:     Open options/Move this icon\nMiddle click: set Attach to the MiniMap on/off.";
    BOOKSTORE_MM_RESETPOSITION = "Reset MiniMap button";
    BOOKSTORE_MM_FIXPOSITION = "Attach MiniMap Button to the MiniMap?";
    BOOKSTORE_MM_FIXPOSITION_COMM = "Protects the MiniMap button from being accidentally moved.";
    BOOKSTORE_MM_SHOWBUTTON = "Show the MiniMap Icon? ( Needs a Restart )";
    BOOKSTORE_MM_SHOWBUTTON_COMM = "Show or hide the MiniMap icon. To take effect, the UI or WoW must be restarted.";
    BOOKSTORE_SETWINPOSITION = "Fix window positions?";
    BOOKSTORE_SETWINPOSITION_COMM = "This also helps if windows are accidentally moved outside of the visible area. To do this, activate this function, then log out and log in again. After that all windows should be in the standard position and you can deactivate this function again.";
    BOOKSTORE_SORT_TITLE = "Title"
    BOOKSTORE_SORT_TITLE_TT = "Sorts the book collection by title. "
    BOOKSTORE_SORT_DATE = "Date"
    BOOKSTORE_SORT_DATE_TT = "Sorts the book collection by date."
    BOOKSTORE_SORT_LOC = "Place"
    BOOKSTORE_SORT_LOC_TT = "Sorts the book collection by where it was found."
    BOOKSTORE_SORT_CREATOR = "Creator"
    BOOKSTORE_SORT_CREATOR_TT = "Sorts the book collection according to the finder."
    BOOKSTORE_SORT_AUTHOR = "Author"
    BOOKSTORE_SORT_AUTHOR_TT = "Sorts the book collection according to the author."
    BOOKSTORE_SORT_TOGGLE = "Asc./\ndesc."
    BOOKSTORE_SORT_TOGGLE_TT = "Switches between ascending and descending order."
    BOOKSTORE_IMPORT_DB_TEXT = "Lemmos BookStore reborn database import"
    BOOKSTORE_IMPORT_DB_KNOWN_ONLY = "Add unknown\nbooks only"
    BOOKSTORE_IMPORT_DB_RESET = "Delete database and\nimport standard data"
    BOOKSTORE_IMPORT_DB_RESET_CONFIRM = "Are you sure you want to delete the existing database\nand replace it with the standard book collection?\n\n!!! This cannot be reversed !!!"
    BOOKSTORE_SEARCH_STATISTICS1 = " books found with a total of "
    BOOKSTORE_SEARCH_STATISTICS2 = " pages."
end
